# Generated by Django 5.1.4 on 2025-01-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user_name',
            new_name='User_name',
        ),
        migrations.RenameField(
            model_name='itemlist',
            old_name='category_name',
            new_name='Category_name',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='category',
            new_name='Category',
        ),
        migrations.AddField(
            model_name='feedback',
            name='Image',
            field=models.ImageField(blank=True, upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='Image',
            field=models.ImageField(upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='Item_name',
            field=models.CharField(max_length=40),
        ),
    ]
