# Generated by Django 5.1.5 on 2025-01-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0002_rename_user_name_feedback_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='BookTable',
            name='Booking_time',
            field=models.TimeField(),  # Use a string
        ),

    ]
