# Generated by Django 5.1.5 on 2025-01-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0003_booktable_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='BookTable',
            name='Booking_time',
            field=models.TimeField(),
        ),
    ]
