# Generated by Django 5.1.5 on 2025-01-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0004_alter_booktable_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='BookTable',
            name='Booking_time',
        ),
    ]
