# Generated by Django 5.1.5 on 2025-01-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0005_remove_booktable_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='Booking_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
