# Generated by Django 5.1.5 on 2025-01-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0006_booktable_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktable',
            name='Booking_time',
        ),
    ]
